"""
Tree generation constants for Codex-AI.

This module contains constants and patterns used for generating JSON tree structures
from Git repositories, including exclusion patterns and output configurations.
"""

from typing import Dict, List, Set

# ===== DIRECTORY EXCLUSION PATTERNS =====
#
# 📊 EXPLANATION:
# Directories to exclude from tree generation.
# Based on old/bin/tree_project.sh EXCLUDE_FOLDERS pattern.
#
# These are typically:
# - Build/dist directories (dist, build, out)
# - Dependencies (node_modules, venv)
# - IDE/editor files (.vscode, .idea)
# - Version control (.git)
# - Cache directories (__pycache__, .tmp)
# - Examples/documentation (examples)

EXCLUDE_DIRECTORIES = [
    "dist",
    "node_modules", 
    "venv",
    "examples",
    ".git",
    ".vscode",
    ".tmp",
    ".github",
    ".aider.tags.cache.v3",
    "__pycache__",
    ".idea",
    ".next",
    ".nuxt",
    "build",
    "out",
    "coverage",
    ".nyc_output",
    "logs",
    ".DS_Store"
]

# ===== TREE OUTPUT CONFIGURATIONS =====
#
# 📊 EXPLANATION:
# Configuration for different types of tree outputs.
# Based on the outputs generated by old/bin/tree_generate_all.sh
#
# Each configuration specifies:
# - filename: Output JSON file name
# - description: What this tree represents
# - source: Which script/function generates it

TREE_OUTPUTS = {
    "project": {
        "filename": "tree_project.json",
        "description": "Complete project structure",
        "source": "tree_project.sh"
    },
    "git_changed": {
        "filename": "tree_git_changed.json", 
        "description": "Files changed in last commit",
        "source": "tree_git_changes.sh"
    },
    "git_removed": {
        "filename": "tree_git_removed.json",
        "description": "Files removed in last commit", 
        "source": "tree_git_changes.sh"
    },
    "git_all": {
        "filename": "tree_git_all.json",
        "description": "All git changes (changed + removed)",
        "source": "tree_git_changes.sh"
    },
    "release_changed": {
        "filename": "tree_release_changed.json",
        "description": "Files changed between releases",
        "source": "tree_git_release_changes.sh"
    },
    "release_removed": {
        "filename": "tree_release_removed.json",
        "description": "Files removed between releases",
        "source": "tree_git_release_changes.sh"
    },
    "release_all": {
        "filename": "tree_release_all.json",
        "description": "All release changes",
        "source": "tree_git_release_changes.sh"
    },
    "git_siblings": {
        "filename": "tree_git_siblings.json",
        "description": "Sibling files of changed files",
        "source": "tree_git_siblings.sh"
    }
}

# ===== GIT CHANGE TYPES =====
#
# 📊 EXPLANATION:
# Git status codes and their meanings for file changes.
# Used to categorize files as changed, removed, or renamed.
#
# Git status codes:
# - A: Added
# - M: Modified  
# - D: Deleted
# - R: Renamed
# - C: Copied
# - U: Unmerged

GIT_CHANGE_TYPES = {
    "CHANGED": ["A", "M", "R", "C", "U"],  # Files that exist after change
    "REMOVED": ["D"],                       # Files that no longer exist
    "RENAMED": ["R"],                       # Special handling for renames
    "ALL": ["A", "M", "D", "R", "C", "U"]  # All possible changes
}

# ===== TREE STRUCTURE PATTERNS =====
#
# 📊 EXPLANATION:
# Patterns for organizing files into tree structures.
# Based on the jq logic in the shell scripts.

TREE_STRUCTURE = {
    "root_files_key": "files",
    "directory_separator": "/",
    "max_depth": None,  # No limit by default
    "sort_arrays": True,
    "include_empty_dirs": False
}

# ===== JQ TRANSFORMATION LOGIC =====
#
# 📊 EXPLANATION:
# The jq logic from shell scripts translated to Python concepts.
# This represents the tree building algorithm used in the original scripts.
#
# Algorithm:
# 1. Split file paths by directory separator
# 2. Build nested structure recursively
# 3. Add files to "files" array in each directory
# 4. Sort all arrays for consistent output

JQ_TREE_ALGORITHM = """
def add_to_path(obj; path; file):
    if path == [] then
        if obj.files then
            obj * {"files": (obj.files + [file])}
        else
            obj * {"files": [file]}
        end
    else
        obj * {
            (path[0]): add_to_path(
                (obj[path[0]] // {}); 
                path[1:];
                file
            )
        }
    end;

reduce .[] as $path (
    {};
    . as $root |
    if ($path | contains("/")) then
        ($path | split("/")) as $parts |
        add_to_path(
            $root;
            $parts[:-1];
            $parts[-1]
        )
    else
        add_to_path($root; []; $path)
    end
) | walk(if type == "array" then sort else . end)
"""

# ===== SIBLING FILE DETECTION =====
#
# 📊 EXPLANATION:
# Configuration for detecting sibling files.
# Based on old/bin/tree_git_siblings.sh logic.
#
# Sibling files are files in the same directory as changed files.
# This helps identify related files that might be affected by changes.

SIBLING_DETECTION = {
    "input_files": {
        "changed_files": "tree_git_changed.json",
        "project_tree": "tree_project.json"
    },
    "output_file": "tree_git_siblings.json",
    "include_subdirectories": True,
    "match_exact_paths": True
}

# ===== DEFAULT CONFIGURATIONS =====
#
# 📊 EXPLANATION:
# Default settings for tree generation operations.

DEFAULT_CONFIG = {
    "output_directory": ".tmp",
    "create_output_dir": True,
    "overwrite_existing": True,
    "validate_git_repo": True,
    "require_jq": False,  # We'll implement in Python, no jq needed
    "sort_output": True,
    "pretty_print": True,
    "indent": 2
}

# ===== VALIDATION PATTERNS =====
#
# 📊 EXPLANATION:
# Patterns for validating file paths and tree structures.

VALIDATION = {
    "valid_filename_chars": r"[a-zA-Z0-9._-]",
    "invalid_path_patterns": [
        r"\.\.\/",  # Parent directory traversal
        r"\/\/",    # Double slashes
        r"^\/"      # Absolute paths (should be relative)
    ],
    "max_path_length": 260,  # Windows compatibility
    "max_filename_length": 255
}

# ===== HELPER FUNCTIONS =====

def is_excluded_directory(dirname: str) -> bool:
    """
    Check if a directory should be excluded from tree generation.
    
    Args:
        dirname: Directory name to check
        
    Returns:
        True if directory should be excluded
    """
    return dirname in EXCLUDE_DIRECTORIES


def get_output_filename(tree_type: str) -> str:
    """
    Get the output filename for a specific tree type.
    
    Args:
        tree_type: Type of tree (project, git_changed, etc.)
        
    Returns:
        Output filename or None if type not found
    """
    config = TREE_OUTPUTS.get(tree_type)
    return config["filename"] if config else None


def is_change_type(status: str, change_category: str) -> bool:
    """
    Check if a Git status code belongs to a change category.
    
    Args:
        status: Git status code (A, M, D, R, etc.)
        change_category: Category to check (CHANGED, REMOVED, etc.)
        
    Returns:
        True if status belongs to category
    """
    return status in GIT_CHANGE_TYPES.get(change_category, [])


def validate_file_path(filepath: str) -> bool:
    """
    Validate a file path for tree generation.
    
    Args:
        filepath: File path to validate
        
    Returns:
        True if path is valid
    """
    import re
    
    # Check length limits
    if len(filepath) > VALIDATION["max_path_length"]:
        return False
    
    # Check for invalid patterns
    for pattern in VALIDATION["invalid_path_patterns"]:
        if re.search(pattern, filepath):
            return False
    
    return True


def split_file_path(filepath: str) -> tuple:
    """
    Split a file path into directory parts and filename.
    
    Args:
        filepath: File path to split
        
    Returns:
        Tuple of (directory_parts, filename)
    """
    if "/" not in filepath:
        return ([], filepath)
    
    parts = filepath.split("/")
    return (parts[:-1], parts[-1])


def get_all_tree_types() -> List[str]:
    """Get all available tree types."""
    return list(TREE_OUTPUTS.keys())


def get_git_change_categories() -> List[str]:
    """Get all Git change categories."""
    return list(GIT_CHANGE_TYPES.keys())


# ===== EXPORT CONSTANTS =====

__all__ = [
    # Main constants
    "EXCLUDE_DIRECTORIES",
    "TREE_OUTPUTS", 
    "GIT_CHANGE_TYPES",
    "TREE_STRUCTURE",
    "JQ_TREE_ALGORITHM",
    "SIBLING_DETECTION",
    "DEFAULT_CONFIG",
    "VALIDATION",
    
    # Helper functions
    "is_excluded_directory",
    "get_output_filename",
    "is_change_type", 
    "validate_file_path",
    "split_file_path",
    "get_all_tree_types",
    "get_git_change_categories"
]
