"""
Configuration management command for Codex-AI.

Handles global configuration settings stored in ~/.config/codex-ai/config.env file.
Supports setting API keys, models, output formats, and other preferences.
"""

import os
from pathlib import Path
from typing import Dict, Any, Optional

from core.config import CodexConfig
from constants.ai import get_cli_model_choices
from constants.output import VALID_OUTPUT_FORMATS


def get_global_config_path() -> Path:
    """Get path to global configuration file (XDG Base Directory compliant)."""
    config_dir = Path.home() / '.config' / 'codex-ai'
    config_dir.mkdir(parents=True, exist_ok=True)
    return config_dir / 'config.env'


def load_global_config() -> Dict[str, str]:
    """Load current global configuration."""
    config_path = get_global_config_path()
    config_data = {}
    
    if config_path.exists():
        with open(config_path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    config_data[key.strip()] = value.strip()
    
    return config_data


def save_global_config(config_data: Dict[str, str]) -> None:
    """Save configuration to global config file."""
    config_path = get_global_config_path()
    
    with open(config_path, 'w', encoding='utf-8') as f:
        f.write("# Codex-AI Global Configuration\n")
        f.write("# Generated by 'codex-ai config' command\n\n")
        
        for key, value in sorted(config_data.items()):
            f.write(f"{key}={value}\n")


def update_global_config(updates: Dict[str, str]) -> None:
    """Update global configuration with new values."""
    current_config = load_global_config()
    current_config.update(updates)
    save_global_config(current_config)


def reset_global_config() -> None:
    """Reset global configuration to defaults."""
    config_path = get_global_config_path()
    if config_path.exists():
        config_path.unlink()
    print("✅ Global configuration reset to defaults")


def show_current_config(config: CodexConfig) -> None:
    """Show current configuration settings."""
    print("🔧 Current Codex-AI Configuration:")
    print()
    
    # API Key (masked for security)
    api_key = config.get_api_key()
    if api_key:
        masked_key = f"{api_key[:8]}...{api_key[-4:]}" if len(api_key) > 12 else "***"
        print(f"🔑 API Key: {masked_key}")
    else:
        print("🔑 API Key: Not set")
    
    # AI Settings
    print(f"🤖 Default Model: {config.get_default_model()}")
    fallback_models = config.get_fallback_models()
    print(f"🔄 Fallback Models: {', '.join(fallback_models)}")
    
    # Output Settings
    print(f"📄 Output Format: {config.get_output_format()}")
    print(f"📁 Output Directory: {config.get_output_dir()}")
    
    # Behavior Settings
    print(f"🔍 Verbose Mode: {config.get_verbose()}")
    print(f"⏱️ Git Timeout: {config.get_git_timeout()}s")
    print(f"🤖 AI Timeout: {config.get_ai_timeout()}s")
    print(f"🔄 AI Retry Attempts: {config.get_ai_retry_attempts()}")
    
    # Performance Settings
    print(f"💾 Cache Enabled: {config.is_cache_enabled()}")
    print(f"⚡ Parallel Processing: {config.is_parallel_processing_enabled()}")
    
    # Global config file location
    global_config_path = get_global_config_path()
    print()
    print(f"📍 Global config file: {global_config_path}")
    print(f"📊 File exists: {'Yes' if global_config_path.exists() else 'No'}")


def validate_model(model: str) -> bool:
    """Validate AI model name (case-insensitive)."""
    valid_models = get_cli_model_choices()
    # Support both uppercase keys and lowercase user input
    valid_models_lower = [m.lower() for m in valid_models]
    return model.upper() in valid_models or model.lower() in valid_models_lower


def validate_output_format(format_name: str) -> bool:
    """Validate output format."""
    valid_formats = [fmt.lower() for fmt in VALID_OUTPUT_FORMATS]
    return format_name.lower() in valid_formats


def validate_boolean(value: str) -> bool:
    """Validate boolean string value."""
    return value.lower() in ['true', 'false']


def parse_fallback_models(models_str: str) -> list:
    """Parse comma-separated fallback models."""
    models = [model.strip() for model in models_str.split(',')]
    for model in models:
        if not validate_model(model):
            raise ValueError(f"Invalid model: {model}")
    return models


def run_config(args, config: CodexConfig) -> int:
    """Run configuration management command."""
    try:
        # Handle --list option
        if args.list:
            show_current_config(config)
            return 0
        
        # Handle --reset option
        if args.reset:
            reset_global_config()
            return 0
        
        # Collect configuration updates
        updates = {}
        
        # API Key
        if args.api_key:
            if not args.api_key.startswith('sk-ant-'):
                print("⚠️ Warning: API key should start with 'sk-ant-'")
            updates['ANTHROPIC_API_KEY'] = args.api_key
            print("✅ API key updated")
        
        # AI Model
        if args.model:
            if not validate_model(args.model):
                print(f"❌ Error: Invalid model '{args.model}'")
                valid_models = get_cli_model_choices()
                print(f"Valid models: {', '.join(valid_models)}")
                return 1
            updates['CODEX_DEFAULT_MODEL'] = args.model
            print(f"✅ Default model set to: {args.model}")
        
        # Fallback Models
        if args.fallback_models:
            try:
                models = parse_fallback_models(args.fallback_models)
                updates['CODEX_FALLBACK_MODELS'] = args.fallback_models
                print(f"✅ Fallback models set to: {', '.join(models)}")
            except ValueError as e:
                print(f"❌ Error: {e}")
                return 1
        
        # Output Format
        if args.output_format:
            if not validate_output_format(args.output_format):
                print(f"❌ Error: Invalid output format '{args.output_format}'")
                valid_formats = [fmt.lower() for fmt in VALID_OUTPUT_FORMATS]
                print(f"Valid formats: {', '.join(valid_formats)}")
                return 1
            updates['CODEX_OUTPUT_FORMAT'] = args.output_format
            print(f"✅ Output format set to: {args.output_format}")
        
        # Output Directory
        if args.output_dir:
            updates['CODEX_OUTPUT_DIR'] = args.output_dir
            print(f"✅ Output directory set to: {args.output_dir}")
        
        # Verbose Mode
        if args.verbose:
            if not validate_boolean(args.verbose):
                print("❌ Error: Verbose must be 'true' or 'false'")
                return 1
            updates['CODEX_VERBOSE'] = args.verbose
            print(f"✅ Verbose mode set to: {args.verbose}")
        
        # Git Timeout
        if args.git_timeout:
            if args.git_timeout <= 0:
                print("❌ Error: Git timeout must be positive")
                return 1
            updates['CODEX_GIT_TIMEOUT'] = str(args.git_timeout)
            print(f"✅ Git timeout set to: {args.git_timeout}s")
        
        # AI Timeout
        if args.ai_timeout:
            if args.ai_timeout <= 0:
                print("❌ Error: AI timeout must be positive")
                return 1
            updates['CODEX_AI_TIMEOUT'] = str(args.ai_timeout)
            print(f"✅ AI timeout set to: {args.ai_timeout}s")
        
        # AI Retry Attempts
        if args.ai_retry_attempts:
            if args.ai_retry_attempts <= 0:
                print("❌ Error: AI retry attempts must be positive")
                return 1
            updates['CODEX_AI_RETRY_ATTEMPTS'] = str(args.ai_retry_attempts)
            print(f"✅ AI retry attempts set to: {args.ai_retry_attempts}")
        
        # Apply updates if any
        if updates:
            update_global_config(updates)
            print()
            print("🎉 Configuration updated successfully!")
            print(f"📍 Saved to: {get_global_config_path()}")
            print()
            print("💡 Use 'codex-ai config --list' to view current settings")
        else:
            print("ℹ️ No configuration changes specified")
            print("💡 Use 'codex-ai config --help' to see available options")
        
        return 0
        
    except Exception as e:
        print(f"❌ Error managing configuration: {e}")
        return 1


# Export main function
__all__ = ['run_config']
